### ISSUE TITLE
After installing the module, I am unable to go to contacts page. I get Odoo Server Error

### ISSUE THREAD

**Issue by M65D85** [OCA/survey#30] opened 2019-07-24 16:19 UTC
Below is the error message I am prompted with. Please note that the module did not install properly. So I had to uninstall it. I am on Odoo CE version 12 hosted on AWS.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/api.py", line 745, in call_kw
    return _call_kw_model(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/api.py", line 718, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/models.py", line 1376, in load_views
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/models.py", line 1376, in <dictcomp>
    for [v_id, v_type] in views
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/addons/mail/models/mail_thread.py", line 410, in fields_view_get
    res = super(MailThread, self).fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/models.py", line 1462, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 1096, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-12.0.post20190618-py3.7.egg/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `survey_input_count` does not exist

Error context:
View `res.partner.form`
[view_id: 113, xml_id: base.view_partner_form, model: res.partner, parent_id: n/a]

**Comment by pedrobaeza** [comment] 2019-07-24 16:21
It seems you haven't restarted your Odoo service.

**Comment by M65D85** [comment] 2019-07-24 16:22
okay let me try

**Comment by M65D85** [comment] 2019-07-24 16:27
I restarted the Odoo services by typing this sudo /opt/bitnami/ctlscript.sh restart. But still the error is there

**Comment by pedrobaeza** [comment] 2019-07-24 16:29
Please try to reproduce the problem in OCA runbot following the link in the README. I'm pretty sure the problem is in your deployment.

**Comment by M65D85** [comment] 2019-07-24 16:45
Okay, I deployed it using import module on Odoo. After which it gave me this error: 


Error while importing module 'partner_survey': 'Error while validating constraint\n\nField `survey_input_count` does not exist\n\nError context:\nView `Partner Form with survey answers`\n[view_id: 1704, xml_id: n/a, model: res.partner, parent_id: 113]\nNone\n<record id="view_partner_form" model="ir.ui.view">\n <field name="name">Partner Form with survey answers</field>\n <field name="model">res.partner</field>\n <field name="inherit_id" ref="base.view_partner_form"/>\n <field name="arch" type="xml">\n <div class="oe_button_box" position="inside">\n <button name="%(partner_survey.act_partner_survey_input)d" type="action" class="oe_stat_button oe_inline" icon="fa-list-alt">\n <field name="survey_input_count" widget="statinfo" string="Surveys"/>\n </button>\n </div>\n </field>\n</record>\n/tmp/tmpx875jhz3/partner_survey/views/res_partner_view.xml\n12'
--

**Comment by pedrobaeza** [comment] 2019-07-24 16:49
Then that's the problem. That option is only valid for data modules, not the rest.

Closing as no valid issue.

**Closed as completed by pedrobaeza** 2019-07-24 16:49 UTC

**Comment by M65D85** [comment] 2019-07-24 16:51
Oh, my bad. I was under the impression I could import it from there. But would you be so kind enough to tell me what the fix for this is?

**Comment by pedrobaeza** [comment] 2019-07-24 16:54
Install it properly putting on addons path in your server.

**Comment by M65D85** [comment] 2019-07-24 16:55
Cool! Thanks!
